# Generated by Django 5.2.5 on 2025-08-28 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(default='ETH', max_length=10)),
                ('is_testnet', models.BooleanField(default=False)),
                ('block_explorer_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockchain',
                'verbose_name_plural': 'Blockchains',
                'ordering': ['chain_id'],
            },
        ),
        migrations.CreateModel(
            name='RpcProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpc_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority providers are preferred')),
                ('rate_limit', models.IntegerField(blank=True, help_text='Requests per second limit', null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_providers', to='chains.chain')),
            ],
            options={
                'verbose_name': 'RPC Provider',
                'verbose_name_plural': 'RPC Providers',
                'ordering': ['chain', '-priority', 'rpc_url'],
                'indexes': [models.Index(fields=['chain', 'enabled', '-priority'], name='chains_rpcp_chain_i_00ce35_idx')],
            },
        ),
    ]
