# Generated by Django 5.2.5 on 2025-08-28 15:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField(db_index=True)),
                ('block_hash', models.CharField(db_index=True, max_length=66)),
                ('parent_hash', models.CharField(max_length=66)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('miner', models.CharField(blank=True, max_length=42, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('total_difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('gas_limit', models.BigIntegerField()),
                ('gas_used', models.BigIntegerField()),
                ('base_fee_per_gas', models.BigIntegerField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('transactions_root', models.CharField(blank=True, max_length=66)),
                ('state_root', models.CharField(blank=True, max_length=66)),
                ('receipts_root', models.CharField(blank=True, max_length=66)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='chains.chain')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['-block_number'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('transaction_index', models.IntegerField()),
                ('from_address', models.CharField(db_index=True, max_length=42)),
                ('to_address', models.CharField(blank=True, db_index=True, max_length=42, null=True)),
                ('value', models.CharField(max_length=100)),
                ('gas', models.BigIntegerField()),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('max_fee_per_gas', models.BigIntegerField(blank=True, null=True)),
                ('max_priority_fee_per_gas', models.BigIntegerField(blank=True, null=True)),
                ('nonce', models.BigIntegerField()),
                ('input_data', models.TextField(blank=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('effective_gas_price', models.BigIntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, db_index=True, max_length=42, null=True)),
                ('logs_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blocks.block')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chains.chain')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['block', 'transaction_index'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.IntegerField()),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=66), blank=True, default=list, size=4)),
                ('data', models.TextField(blank=True)),
                ('removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='blocks.block')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chains.chain')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='blocks.transaction')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['block', 'transaction', 'log_index'],
            },
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['chain', '-block_number'], name='blocks_bloc_chain_i_91221f_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['timestamp'], name='blocks_bloc_timesta_e7b9e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('chain', 'block_hash'), ('chain', 'block_number')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['chain', 'from_address'], name='blocks_tran_chain_i_1053ee_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['chain', 'to_address'], name='blocks_tran_chain_i_07d684_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['chain', 'contract_address'], name='blocks_tran_chain_i_246d75_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['chain', 'address'], name='blocks_log_chain_i_3808e4_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['topics'], name='blocks_log_topics_3ebe78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('chain', 'block', 'transaction', 'log_index')},
        ),
    ]
