# Generated by Django 5.2.5 on 2025-08-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0001_initial"),
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_block", models.BigIntegerField(db_index=True)),
                ("end_block", models.BigIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("complete", "Complete"),
                            ("incomplete", "Incomplete"),
                            ("repairing", "Repairing"),
                            ("failed", "Failed"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("completeness_percentage", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("missing_blocks", models.JSONField(default=list)),
                ("file_path", models.TextField(blank=True)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("compression_ratio", models.FloatField(default=1.0)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("total_blocks", models.IntegerField(default=0)),
                ("total_transactions", models.IntegerField(default=0)),
                ("chunk_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_repair_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="chains.chain"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "ordering": ["-chunk_date", "-start_block"],
            },
        ),
        migrations.CreateModel(
            name="ChunkRepairLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("blocks_attempted", models.IntegerField(default=0)),
                ("blocks_repaired", models.IntegerField(default=0)),
                ("missing_blocks_before", models.JSONField(default=list)),
                ("missing_blocks_after", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="repair_logs", to="blocks.chunk"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk Repair Log",
                "verbose_name_plural": "Chunk Repair Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["chain", "-chunk_date"], name="blocks_chun_chain_i_2a67ca_idx"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["status"], name="blocks_chun_status_523130_idx"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["completeness_percentage"], name="blocks_chun_complet_806906_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("chain", "start_block", "end_block")},
        ),
    ]
