# Generated by Django 5.2.5 on 2025-08-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cluster_name', models.CharField(max_length=255)),
                ('namespace', models.CharField(default='default', max_length=255)),
                ('kubeconfig', models.TextField(help_text='Base64 encoded kubeconfig or path to kubeconfig file')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kubernetes Credential',
                'verbose_name_plural': 'Kubernetes Credentials',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('node_type', models.CharField(choices=[('archive', 'Archive Node'), ('full', 'Full Node'), ('light', 'Light Node'), ('validator', 'Validator Node')], default='full', max_length=20)),
                ('client_software', models.CharField(help_text='e.g., geth, erigon, reth, etc.', max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('deployment_name', models.CharField(blank=True, max_length=255)),
                ('pvc_name', models.CharField(blank=True, max_length=255)),
                ('storage_size_gb', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('syncing', 'Syncing'), ('running', 'Running'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('internal_rpc_url', models.URLField(blank=True, null=True)),
                ('external_rpc_url', models.URLField(blank=True, null=True)),
                ('ws_url', models.URLField(blank=True, null=True)),
                ('sync_progress', models.FloatField(default=0.0, help_text='Sync progress as percentage (0-100)')),
                ('current_block_height', models.BigIntegerField(blank=True, null=True)),
                ('resource_requests', models.JSONField(blank=True, default=dict, help_text='CPU and memory requests for k8s deployment')),
                ('resource_limits', models.JSONField(blank=True, default=dict, help_text='CPU and memory limits for k8s deployment')),
                ('extra_args', models.JSONField(blank=True, default=list, help_text='Additional command line arguments for the node')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chains.chain')),
                ('kube_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.kubecredential')),
            ],
            options={
                'verbose_name': 'Blockchain Node',
                'verbose_name_plural': 'Blockchain Nodes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chain', 'status'], name='nodes_node_chain_i_2b926c_idx'), models.Index(fields=['kube_credential', 'status'], name='nodes_node_kube_cr_381336_idx')],
            },
        ),
    ]
