# Generated by Django 5.2.5 on 2025-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='consensus_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_client',
            field=models.CharField(choices=[('lighthouse', 'Lighthouse'), ('prysm', 'Prysm'), ('teku', 'Teku'), ('nimbus', 'Nimbus'), ('lodestar', 'Lodestar')], default='lighthouse', help_text='Consensus layer client (e.g., lighthouse, prysm)', max_length=20),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_deployment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_head_slot',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_pvc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_storage_size_gb',
            field=models.IntegerField(default=200, help_text='Storage size for consensus client data'),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_sync_progress',
            field=models.FloatField(default=0.0, help_text='Consensus client sync progress as percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='node',
            name='consensus_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_client',
            field=models.CharField(choices=[('reth', 'Reth'), ('geth', 'Geth'), ('erigon', 'Erigon'), ('besu', 'Besu'), ('nethermind', 'Nethermind')], default='reth', help_text='Execution layer client (e.g., reth, geth)', max_length=20),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_deployment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_pvc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_rpc_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_sync_progress',
            field=models.FloatField(default=0.0, help_text='Execution client sync progress as percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='execution_ws_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='client_software',
            field=models.CharField(blank=True, help_text='Deprecated: Use execution_client instead', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='deployment_name',
            field=models.CharField(blank=True, help_text='Deprecated: Use execution_deployment_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='external_rpc_url',
            field=models.URLField(blank=True, help_text='Deprecated: Use execution_rpc_url', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='internal_rpc_url',
            field=models.URLField(blank=True, help_text='Deprecated: Use execution_rpc_url', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='pvc_name',
            field=models.CharField(blank=True, help_text='Deprecated: Use execution_pvc_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='storage_size_gb',
            field=models.IntegerField(default=2000, help_text='Storage size for execution client data'),
        ),
        migrations.AlterField(
            model_name='node',
            name='sync_progress',
            field=models.FloatField(default=0.0, help_text='Deprecated: Use execution_sync_progress and consensus_sync_progress'),
        ),
        migrations.AlterField(
            model_name='node',
            name='version',
            field=models.CharField(blank=True, help_text='Deprecated: Use execution_version instead', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='ws_url',
            field=models.URLField(blank=True, help_text='Deprecated: Use execution_ws_url', null=True),
        ),
    ]
