# Generated by Django 5.2.5 on 2025-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_consensus_api_url_node_consensus_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='storage_class',
            field=models.CharField(blank=True, default='iota-slush', help_text='Kubernetes storage class for PVCs (e.g., iota-slush)', max_length=100),
        ),
    ]
