# Generated by Django 5.2.5 on 2025-08-28 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_node_storage_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "execution_sync_progress",
                    models.FloatField(default=0.0, help_text="Execution client sync progress (0-100)"),
                ),
                (
                    "consensus_sync_progress",
                    models.FloatField(default=0.0, help_text="Consensus client sync progress (0-100)"),
                ),
                (
                    "current_block_height",
                    models.BigIntegerField(blank=True, help_text="Current execution block height", null=True),
                ),
                (
                    "highest_block_height",
                    models.BigIntegerField(blank=True, help_text="Target execution block height", null=True),
                ),
                (
                    "consensus_head_slot",
                    models.BigIntegerField(blank=True, help_text="Current consensus slot", null=True),
                ),
                ("node_status", models.CharField(help_text="Node status at time of recording", max_length=20)),
                ("is_syncing", models.BooleanField(default=True, help_text="Whether node was actively syncing")),
                ("peers_count", models.IntegerField(blank=True, help_text="Number of connected peers", null=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional metrics or error information"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sync_history", to="nodes.node"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Status History",
                "verbose_name_plural": "Sync Status Histories",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="nodes_syncs_timesta_3dbdcf_idx"),
                    models.Index(fields=["node", "-timestamp"], name="nodes_syncs_node_id_99a69b_idx"),
                ],
            },
        ),
    ]
