# Generated by Django 5.2.5 on 2025-09-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_add_sync_status_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="consensus_node_selector",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated node names to target for consensus client (e.g., vega,nova,iota)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="execution_node_selector",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated node names to target for execution client (e.g., vega,nova,iota)",
                max_length=255,
            ),
        ),
    ]
